#Abel's notes
-

MACHINE LEARNING TASK - predict House Prices -> (Regression)

##Todo
-

# Setup Dependencies

In [5]:
!pip install kaggle

In [6]:
!mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [8]:
!cp kaggle.json ~/.kaggle/kaggle.json

In [9]:
!chmod 600 ~/.kaggle/kaggle.json

In [10]:
!kaggle competitions download -c house-prices-advanced-regression-techniques

  0% 0.00/199k [00:00<?, ?B/s]
100% 199k/199k [00:00<00:00, 99.0MB/s]


In [11]:
!unzip house-prices-advanced-regression-techniques.zip

Archive:  house-prices-advanced-regression-techniques.zip
  inflating: data_description.txt    
  inflating: sample_submission.csv   
  inflating: test.csv                
  inflating: train.csv               


# Load Data and Do EDA

In [12]:
!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

     / 17.8 MB 35.7 MB/s 0:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.1/686.1 kB 18.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 26.1 MB/s eta 0:00:00
  Created wheel for ydata-profiling: filename=ydata_profiling-0.0.dev0-py2.py3-none-any.whl size=359549 sha256=ca131fe618ad391c7054cf78e61194410000e84bfee6a8b429e04fc1ca2cad5c
  Stored in directory: /tmp/pip-ephem-wheel-cache-vjq02qki/wheels/07/29/61/f533cc7cbd0a97efb2d1b94d3254a3e859a949367ba842577b
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27080 sha256=1d4723b7f33a180e4bda293e5b64d7f6a5f9220a546edc6a8aa6f46d4a137f20
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built ydata-profiling htmlmin


In [13]:
import pandas as pd
from pandas_profiling import ProfileReport

<ipython-input-13-98f09099f855>:2: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport


In [14]:
df = pd.read_csv('train.csv')

In [15]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [17]:
profile = ProfileReport(df, title='House Prices')

In [18]:
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [19]:
train_df = df.copy()

In [20]:
train_df['SalePrice'].mean()

180921.19589041095

In [21]:
test_df = pd.read_csv('test.csv')

In [22]:
test_df['SalePrice'] = pd.Series([train_df['SalePrice'].mean()] * len(train_df))

In [23]:
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            HLS    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition     SalePrice  
0         6   2010        WD         Normal  180921.19589  
1         6   2010        WD         Normal  180921.19589  
2         3   2010        WD         Normal  180921.19589  
3         6   2010        WD         Normal  180921.19589  
4         1   2010        WD         Normal  180921.19589  
...     ...    ...       ...            ...           ...  
1454      6   2006        WD         Normal  180921.19589  
1455      4   2006        WD        Abnorml  180921.19589  
1456      9   2006        WD        Abnorml  180921.19589  
1457      7   2006        WD         Normal  180921.19589  
1458     11   2006        WD         Normal  180921.19589  

[1459 rows x 81 columns]

In [24]:
test_df[['Id', 'SalePrice']]

Id     SalePrice
0     1461  180921.19589
1     1462  180921.19589
2     1463  180921.19589
3     1464  180921.19589
4     1465  180921.19589
...    ...           ...
1454  2915  180921.19589
1455  2916  180921.19589
1456  2917  180921.19589
1457  2918  180921.19589
1458  2919  180921.19589

[1459 rows x 2 columns]

# First Try with mean prediction

In [25]:
test_df[['Id', 'SalePrice']].to_csv('average_prediction.csv', index=False)

In [27]:
!kaggle competitions submit -c house-prices-advanced-regression-techniques -f average_prediction.csv -m "average-prediction"

100% 34.2k/34.2k [00:00<00:00, 118kB/s]
Successfully submitted to House Prices - Advanced Regression Techniques

In [29]:
from copy import deepcopy
train_df_sub = deepcopy(train_df[['MSSubClass', 'LotFrontage', 'SalePrice']])
train_df_sub

MSSubClass  LotFrontage  SalePrice
0             60         65.0     208500
1             20         80.0     181500
2             60         68.0     223500
3             70         60.0     140000
4             60         84.0     250000
...          ...          ...        ...
1455          60         62.0     175000
1456          20         85.0     210000
1457          70         66.0     266500
1458          20         68.0     142125
1459          20         75.0     147500

[1460 rows x 3 columns]

In [34]:
train_df_sub.mean()

MSSubClass         56.897260
LotFrontage        70.049958
SalePrice      180921.195890
dtype: float64

In [35]:
train_df_sub = train_df_sub.fillna(train_df_sub.mean())

In [36]:
X_train, y_train = train_df_sub.to_numpy()[:, :-1], train_df_sub.to_numpy()[:, -1]

In [37]:
X_train

array([[60., 65.],
       [20., 80.],
       [60., 68.],
       ...,
       [70., 66.],
       [20., 68.],
       [20., 75.]])

In [38]:
y_train

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

# Model
- Feature and Target values - X, y

In [39]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression().fit(X_train, y_train)

lr

LinearRegression()

In [40]:
lr.coef_

array([  75.96942776, 1260.11397803])

In [41]:
lr.intercept_

88327.8118861935

In [42]:
train_df_sub['Linear Prediction'] = lr.predict(X_train)
train_df_sub

MSSubClass  LotFrontage  SalePrice  Linear Prediction
0             60         65.0     208500      174793.386124
1             20         80.0     181500      190656.318684
2             60         68.0     223500      178573.728058
3             70         60.0     140000      169252.510511
4             60         84.0     250000      198735.551706
...          ...          ...        ...                ...
1455          60         62.0     175000      171013.044190
1456          20         85.0     210000      196956.888574
1457          70         66.0     266500      176813.194379
1458          20         68.0     142125      175534.950948
1459          20         75.0     147500      184355.748794

[1460 rows x 4 columns]

# Evaluate Performance on Test Set

In [43]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_train, train_df_sub['Linear Prediction'])

54381.25047406032

In [44]:
test_df_sub = deepcopy(test_df[['MSSubClass', 'LotFrontage']])
test_df_sub

MSSubClass  LotFrontage
0             20         80.0
1             20         81.0
2             60         74.0
3             60         78.0
4            120         43.0
...          ...          ...
1454         160         21.0
1455         160         21.0
1456          20        160.0
1457          85         62.0
1458          60         74.0

[1459 rows x 2 columns]

In [45]:
test_df_sub = test_df_sub.fillna(test_df_sub.mean())
test_df_sub

MSSubClass  LotFrontage
0             20         80.0
1             20         81.0
2             60         74.0
3             60         78.0
4            120         43.0
...          ...          ...
1454         160         21.0
1455         160         21.0
1456          20        160.0
1457          85         62.0
1458          60         74.0

[1459 rows x 2 columns]

In [46]:
X_test = test_df_sub.to_numpy()
X_test

array([[ 20.,  80.],
       [ 20.,  81.],
       [ 60.,  74.],
       ...,
       [ 20., 160.],
       [ 85.,  62.],
       [ 60.,  74.]])

In [50]:
test_df['SalePrice'] = lr.predict(X_test)
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            HLS    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition      SalePrice  
0         6   2010        WD         Normal  190656.318684  
1         6   2010        WD         Normal  191916.432662  
2         3   2010        WD         Normal  186134.411926  
3         6   2010        WD         Normal  191174.867838  
4         1   2010        WD         Normal  151629.044272  
...     ...    ...       ...            ...            ...  
1454      6   2006        WD         Normal  126945.313866  
1455      4   2006        WD        Abnorml  126945.313866  
1456      9   2006        WD        Abnorml  291465.436927  
1457      7   2006        WD         Normal  172912.279884  
1458     11   2006        WD         Normal  186134.411926  

[1459 rows x 81 columns]

# Submit to Kaggle

In [51]:
test_df[['Id', 'SalePrice']].to_csv('linear-prediction.csv', index=False)

In [52]:
!kaggle competitions submit -c house-prices-advanced-regression-techniques -f linear-prediction.csv -m "linear-prediction"

100% 33.7k/33.7k [00:00<00:00, 148kB/s]
Successfully submitted to House Prices - Advanced Regression Techniques